# Generated by Django 5.2.1 on 2025-06-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Horário')),
                ('event_type', models.CharField(choices=[('INICIO', 'Início de Aula'), ('FIM', 'Fim de Aula'), ('RECREIO', 'Recreio'), ('TURNO', 'Troca de Turno')], max_length=10, verbose_name='Tipo de Evento')),
                ('days_of_week', models.CharField(help_text='Ex: MON,TUE,WED para segunda, terça e quarta', max_length=21, verbose_name='Dias da Semana')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Término')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
