# Generated by Django 5.2.1 on 2025-06-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alarmschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmschedule',
            name='days_of_week',
            field=models.CharField(help_text='Ex: SEG,TER,QUA para segunda, terça e quarta', max_length=21, verbose_name='Dias da Semana'),
        ),
    ]
