# Generated by Django 5.2.1 on 2025-06-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_alarmschedule_days_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComandoESP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando', models.CharField(default='desligar', max_length=10)),
            ],
        ),
    ]
