# Generated by Django 4.2 on 2025-06-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comandoesp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SirenStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on', models.BooleanField(default=False)),
            ],
        ),
    ]
