# Generated by Django 4.2 on 2025-06-29 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sirenstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.AlterModelOptions(
            name='comandoesp',
            options={'verbose_name': 'Comando ESP', 'verbose_name_plural': 'Comandos ESP'},
        ),
        migrations.AddField(
            model_name='alarmschedule',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comandoesp',
            name='executado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comandoesp',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sirenstatus',
            name='last_activated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alarmschedule',
            name='days_of_week',
            field=models.CharField(max_length=27, verbose_name='Dias da Semana'),
        ),
    ]
