# Generated by Django 4.2 on 2025-06-29 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_model_alter_comandoesp_options_and_more'),
    ]

    operations = [
    ]
