# Generated by Django 4.2 on 2025-06-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_force_active_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='comandoesp',
            name='duration',
            field=models.IntegerField(default=60, verbose_name='Duração (minutos)'),
        ),
        migrations.AddField(
            model_name='comandoesp',
            name='source',
            field=models.CharField(default='unknown', max_length=20, verbose_name='Origem do comando'),
        ),
    ]
