# Generated by Django 5.2.3 on 2025-07-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_comandoesp_duration_comandoesp_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='comandoesp',
            name='update',
            field=models.CharField(default='normal'),
        ),
    ]
