# Generated by Django 4.2 on 2025-06-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_comandoesp_duration_comandoesp_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comandoesp',
            options={},
        ),
        migrations.RemoveField(
            model_name='comandoesp',
            name='duration',
        ),
        migrations.AlterField(
            model_name='comandoesp',
            name='source',
            field=models.CharField(blank=True, default='unknown', max_length=20, null=True),
        ),
    ]
