# Generated by Django 4.2 on 2025-06-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_comandoesp_options_remove_comandoesp_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmschedule',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
